### PR TITLE
Fallback on basic ANSI terminal support.

### LINKED ISSUE #44: Doesn't work on FreeBSD
I cannot get this to work on FreeBSD.  I'm not sure what it is expecting to find but I know FreeBSD does use a terminfo database which a comment in `searcher.rs` says it doesn't support.  Is there a way to add support for the terminfo database, or else can I point it to some other files to convince it to work, or could there be some default fallback behaviour (assume VT100?) ?

### PR DESCRIPTION
**Pull request by Stebalien**
Fixes #44

### CODE REVIEW

**Comment by Stebalien** [comment]
/cc @Parakleta, @alexcrichton, @alexreg

Thoughts? This should fix term on FreeBSD (and should make it more reliably color output everywhere). I'll get around to my new shiny version someday but that could take a while.

---

Basically, if looking up the terminfo database fails, term will now check to see if the terminal name matches a known ANSI-capable terminal name (by prefix). If it does, it uses a predefined minimal ANSI termcap definition.

**Comment by alexreg** [comment]
Looks good. I appreciate that full support on BSD-like systems will take a lot of effort, but this will hold us over for now. :)

**Comment by Parakleta** [comment]
I don't have an active rust project to test this against for now so I don't have any feedback, but I wanted to say thanks for the effort.

**Comment by alexcrichton** [comment]
Seems reasonable!

**Pull request merged**
